// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: calculator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Calculate(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
	CalculatePrimes(ctx context.Context, in *PrimeCalculatorRequest, opts ...grpc.CallOption) (CalculatorService_CalculatePrimesClient, error)
	CalculateAvg(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateAvgClient, error)
	CalculateMax(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateMaxClient, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Calculate(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) CalculatePrimes(ctx context.Context, in *PrimeCalculatorRequest, opts ...grpc.CallOption) (CalculatorService_CalculatePrimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[0], "/calculator.CalculatorService/CalculatePrimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculatePrimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_CalculatePrimesClient interface {
	Recv() (*CalculatorResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculatePrimesClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculatePrimesClient) Recv() (*CalculatorResponse, error) {
	m := new(CalculatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) CalculateAvg(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateAvgClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[1], "/calculator.CalculatorService/CalculateAvg", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculateAvgClient{stream}
	return x, nil
}

type CalculatorService_CalculateAvgClient interface {
	Send(*PrimeCalculatorRequest) error
	CloseAndRecv() (*AvgResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculateAvgClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculateAvgClient) Send(m *PrimeCalculatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceCalculateAvgClient) CloseAndRecv() (*AvgResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AvgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) CalculateMax(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[2], "/calculator.CalculatorService/CalculateMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculateMaxClient{stream}
	return x, nil
}

type CalculatorService_CalculateMaxClient interface {
	Send(*PrimeCalculatorRequest) error
	Recv() (*CalculatorResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculateMaxClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculateMaxClient) Send(m *PrimeCalculatorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceCalculateMaxClient) Recv() (*CalculatorResponse, error) {
	m := new(CalculatorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
// All implementations must embed UnimplementedCalculatorServiceServer
// for forward compatibility
type CalculatorServiceServer interface {
	Calculate(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
	CalculatePrimes(*PrimeCalculatorRequest, CalculatorService_CalculatePrimesServer) error
	CalculateAvg(CalculatorService_CalculateAvgServer) error
	CalculateMax(CalculatorService_CalculateMaxServer) error
	mustEmbedUnimplementedCalculatorServiceServer()
}

// UnimplementedCalculatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (UnimplementedCalculatorServiceServer) Calculate(context.Context, *CalculatorRequest) (*CalculatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedCalculatorServiceServer) CalculatePrimes(*PrimeCalculatorRequest, CalculatorService_CalculatePrimesServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculatePrimes not implemented")
}
func (UnimplementedCalculatorServiceServer) CalculateAvg(CalculatorService_CalculateAvgServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateAvg not implemented")
}
func (UnimplementedCalculatorServiceServer) CalculateMax(CalculatorService_CalculateMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateMax not implemented")
}
func (UnimplementedCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {}

// UnsafeCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServiceServer will
// result in compilation errors.
type UnsafeCalculatorServiceServer interface {
	mustEmbedUnimplementedCalculatorServiceServer()
}

func RegisterCalculatorServiceServer(s grpc.ServiceRegistrar, srv CalculatorServiceServer) {
	s.RegisterService(&CalculatorService_ServiceDesc, srv)
}

func _CalculatorService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Calculate(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_CalculatePrimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeCalculatorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).CalculatePrimes(m, &calculatorServiceCalculatePrimesServer{stream})
}

type CalculatorService_CalculatePrimesServer interface {
	Send(*CalculatorResponse) error
	grpc.ServerStream
}

type calculatorServiceCalculatePrimesServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculatePrimesServer) Send(m *CalculatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_CalculateAvg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).CalculateAvg(&calculatorServiceCalculateAvgServer{stream})
}

type CalculatorService_CalculateAvgServer interface {
	SendAndClose(*AvgResponse) error
	Recv() (*PrimeCalculatorRequest, error)
	grpc.ServerStream
}

type calculatorServiceCalculateAvgServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculateAvgServer) SendAndClose(m *AvgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceCalculateAvgServer) Recv() (*PrimeCalculatorRequest, error) {
	m := new(PrimeCalculatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_CalculateMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).CalculateMax(&calculatorServiceCalculateMaxServer{stream})
}

type CalculatorService_CalculateMaxServer interface {
	Send(*CalculatorResponse) error
	Recv() (*PrimeCalculatorRequest, error)
	grpc.ServerStream
}

type calculatorServiceCalculateMaxServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculateMaxServer) Send(m *CalculatorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceCalculateMaxServer) Recv() (*PrimeCalculatorRequest, error) {
	m := new(PrimeCalculatorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorService_ServiceDesc is the grpc.ServiceDesc for CalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CalculatorService_Calculate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculatePrimes",
			Handler:       _CalculatorService_CalculatePrimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CalculateAvg",
			Handler:       _CalculatorService_CalculateAvg_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CalculateMax",
			Handler:       _CalculatorService_CalculateMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator.proto",
}
